### ISSUE TITLE
Bottle for emacs-plus 26.2 does not exist

### ISSUE THREAD

**Issue by SergeStinckwich** [d12frosted/homebrew-emacs-plus#133]
```shell
brew upgrade emacs-plus
==> Upgrading 1 outdated package:
d12frosted/emacs-plus/emacs-plus 26.1 -> 26.2
==> Upgrading d12frosted/emacs-plus/emacs-plus
==> Downloading https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-26.2.mojave.bottle.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "emacs-plus"
Download failed: https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-26.2.mojave.bottle.2.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-26.2.tar.xz
Already downloaded: /Users/stinckwich/Library/Caches/Homebrew/downloads/05a30fe5c4ef911a2b621d0b52f071cdbe7288d33d3db00ef1403c7a871eb047--emacs-26.2.tar.xz
==> Downloading https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c62450be1cbee9f11cecba846dd66c7d06/patch-multicolor-font.diff
Already downloaded: /Users/stinckwich/Library/Caches/Homebrew/downloads/7dccd5b8ea0bb2eb29cfb643365489d84c16ea33b1743261be66fa9691733a1e--patch-multicolor-font.diff
==> Patching
==> Applying patch-multicolor-font.diff
patching file src/macfont.m
Hunk #1 succeeded at 2346 (offset -27 lines).
==> ImageMagick PKG_CONFIG_PATH:
/usr/local/opt/imagemagick@6/lib/pkgconfig
==> ./configure --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.2 --with-xml2 --without-dbus --with-gnutl
Last 15 lines from /Users/stinckwich/Library/Logs/Homebrew/emacs-plus/01.configure:
checking for net/if_dl.h... yes
checking for struct ifreq.ifr_flags... yes
checking for struct ifreq.ifr_hwaddr... no
checking for struct ifreq.ifr_netmask... no
checking for struct ifreq.ifr_broadaddr... yes
checking for struct ifreq.ifr_addr... yes
checking for struct ifreq.ifr_addr.sa_len... yes
checking whether gcc understands -MMD -MF... yes
checking for X... libraries /usr/lib, headers /usr/include
checking AppKit/AppKit.h usability... no
checking AppKit/AppKit.h presence... no
checking for AppKit/AppKit.h... no
configure: error: The include files (AppKit/AppKit.h etc) that
are required for a Nextstep build are missing or cannot be compiled.
Either fix this, or re-configure with the option '--without-ns'.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues
```

**Comment by d12frosted** [comment]
Hi @SergeStinckwich, thank you for the report.

Hm... that's interesting because `brew` generated files with double dashes in the name: `
emacs-plus--26.2.mojave.bottle.2.tar.gz`. But when downloading it uses `
emacs-plus-26.2.mojave.bottle.2.tar.gz`.

Just in case, I've duplicated the bottles with a single dash. Would be cool if you retry.

On the other hand, the failure you faced is not related to bottles. 

```
Warning: Bottle installation failed: building from source.
...
configure: error: The include files (AppKit/AppKit.h etc) that
are required for a Nextstep build are missing or cannot be compiled.
Either fix this, or re-configure with the option '--without-ns'.
```

I am not sure why it happens. Can you please run `brew doctor` to check that everything is fine? Maybe you need the latest available version of Xcode for your system version?

**Comment by d12frosted** [comment]
Oh and just realised - I pushed bottle for high sierra to wrong branch :smile_cat: now in master!

**Comment by SergeStinckwich** [comment]
Still have the same error

```shell
brew upgrade emacs-plus
==> Upgrading 1 outdated package:
d12frosted/emacs-plus/emacs-plus 26.1 -> 26.2
==> Upgrading d12frosted/emacs-plus/emacs-plus
==> Downloading https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-26.2.mojave.bottle.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "emacs-plus"
Download failed: https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-26.2.mojave.bottle.2.tar.gz
Warning: Bottle installation failed: building from source.
```

I have last Xcode 10.2.1 installed. ``brew doctor`` shows nothing suspicious.

**Comment by d12frosted** [comment]
Now works the bottle: https://travis-ci.org/d12frosted/homebrew-emacs-plus/jobs/523451797#L1388

Regarding your build failure - I have no clue right now :man_shrugging:

**Comment by SergeStinckwich** [comment]
I was able to dl the bottle now. Thank you !

**Comment by d12frosted** [comment]
Great! @jonhermansen provided the bottle :smile_cat:
