### ISSUE TITLE
Child frame border styles not working on Mojave & HEAD

### ISSUE THREAD

**Issue by d4ncer** [d12frosted/homebrew-emacs-plus#148]
I've been favouring child frames a lot recently (via [`posframe`](https://github.com/tumashu/posframe)) and the only issue I've found with this formulae is the inability to add styling to the borders of these frames. I've confirmed it works on [`emacs-mac`](https://github.com/railwaycat/homebrew-emacsmacport/) running 26.2.

I'm not sure if it's caused by Mojave or `HEAD`: 

```sh
brew install emacs-plus --with-modern-icon --without-spacemacs-icon --HEAD --with-jansson
```

Thank you!

**Comment by Nollo** [comment]
I got it too on High Sierra.

I ended up with `emacs-mac`

**Comment by d12frosted** [comment]
TBH, not sure what you are talking about. Emacs has so many corners and I definitely don't use all of the functionality :) Steps to reproduce?

**Comment by seagle0128** [comment]
@d12frosted I think it's about [chid frames](https://www.gnu.org/software/emacs/manual/html_node/elisp/Child-Frames.html) in 26+. This should be an issue of Emacs itself.

**Comment by d12frosted** [comment]
@seagle0128 thanks! Sure I've seen them in the wild, but never directly used them.

**Comment by d12frosted** [comment]
@seagle0128 and @Nollo is it still an issue?

**Comment by seagle0128** [comment]
@d12frosted The issue has been resolved in the master branch (28.0.50) AFAIK.

**Comment by d12frosted** [comment]
Alright then. I am closing this issue. Thanks everyone (especially GNU Emacs contributors who actually fixed that).

**Comment by Nollo** [comment]
I still have the issue with @27

![image](https://user-images.githubusercontent.com/12733571/100858828-c6c91780-348e-11eb-9986-08281cef058c.png)

I'll check @28 :-)
