### ISSUE TITLE
Could not install --with-native-comp on Monterey

### ISSUE THREAD

**Issue by ModdedGamers** [d12frosted/homebrew-emacs-plus#396]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I was trying to install Emacs 28 for terminal without cocoa and with native comp.

## What happened (include command output)

<pre>
$ brew install -vvv emacs-plus@28 --with-native-comp --without-cocoa
</pre>

<details>
  <summary>Zipped Logs</summary>
[libgccjit.zip](https://github.com/d12frosted/homebrew-emacs-plus/files/7173069/libgccjit.zip)
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.2.12-9-gb19fcef
ORIGIN: https://github.com/Homebrew/brew
HEAD: b19fcef629a45b0c9c198eb47646ea2a2a1623ce
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e79d8126370187be3bd7be6bdbffacf803732113
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /Users/993390/.brew
HOMEBREW_REPOSITORY: /Users/993390/.brew
HOMEBREW_CELLAR: /Users/993390/.brew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 7
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 7
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0.5 build 1205
Git: 2.33.0 => /Users/993390/.brew/opt/git/bin/git
Curl: 7.78.0 => /Users/993390/.brew/opt/curl/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A

</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/993390/.cargo/bin/cargo-install-update-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  six

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
Warning: /usr/bin occurs before /Users/993390/.brew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/Users/993390/.brew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/Users/993390/.brew/bin:$PATH"' >> ~/.zshrc

The following tools exist at both paths:
  ctags
  pp
  git-receive-pack
  python3
  pip3
  bashbug
  git-upload-archive
  git-shell
  git-upload-pack
  git
</pre>

Changing my prefix is not an option for me, as I don't have admin on this machine(school laptop.) Anything else should be standard.

**Comment by ModdedGamers** [comment]
I've resolved the last issue(the one which tells me that my path is messed up), and I'm rerunning the build now. Will let you know in an hour or so if it completes.

**Comment by d12frosted** [comment]
It might be really related to prefix. Does it build for you without native-comp?

**Comment by ModdedGamers** [comment]
Yes it does. I think the problem is with the `libgccjit` build.

**Comment by Cbeck527** [comment]
FYI: this was fixed for me as of https://github.com/Homebrew/homebrew-core/pull/88145

**Comment by d12frosted** [comment]
Seems like the issue was resolved, so please try again. 

BTW, once GitHub CI provides Monterey env, we should migrate to, so we are 100% sure that Monterey is supported.

**Comment by transducer** [comment]
I still get
```
configure: error: The installed libgccjit failed to compile and run a test program using
the libgccjit library; see config.log for the details of the failure.
```
on Montery 12.6.8 after ` brew install emacs-plus@30 --with-native-comp`.

**Comment by verhovsky** [comment]
I get this error running both `brew install --with-native-comp emacs-plus@30` and `brew install --with-native-comp emacs-plus@29` on macOS 14.2.1 on an M1 Macbook Air. I tried doing `brew reinstall libgccjit` and `rm -rf ~/Library/Caches/Homebrew/emacs-plus*` but it didn't help.

I just removed the `--with-native-comp` and that works at least:

```sh
brew install emacs-plus@29
```

**Comment by mholson** [comment]
> I get this error running both `brew install --with-native-comp emacs-plus@30` and `brew install --with-native-comp emacs-plus@29` on macOS 14.2.1 on an M1 Macbook Air. I tried doing `brew reinstall libgccjit` and `rm -rf ~/Library/Caches/Homebrew/emacs-plus*` but it didn't help.
> 
> I just removed the `--with-native-comp` and that works at least:
> 
> ```shell
> brew install emacs-plus@29
> ```

I have the **same issue** on a MacBook 12 (intel) running Ventura 13.6.3 when I tried to upgrade from emacs-plus@28 to emacs-plus@29 by:
- [x] **brew uninstall => install of of emacs-plus** `brew install emacs-plus --with-native-comp` 
- [x] **brew uninstall => install gcc and libgccjit** 
- [x] removing and reinstalling homebrew
